import type { CSSProperties } from "react";

export const s = {
  body: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    marginTop: 18,
  } satisfies CSSProperties,
  dropzone: (dragging: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "32px 20px",
    borderRadius: 8,
    border: "1.5px dashed " + (dragging ? "var(--accent)" : "var(--border-strong)"),
    background: dragging ? "var(--accent-bg)" : "var(--bg-surface)",
    color: "var(--text-muted)",
    fontSize: 13,
    cursor: "pointer",
    textAlign: "center",
  }),
  extracted: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--ok)",
  } satisfies CSSProperties,
  tokens: { marginLeft: "auto", color: "var(--text-muted)" } satisfies CSSProperties,
  skippedBox: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 14,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  skippedTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--warning)",
    marginBottom: 8,
  } satisfies CSSProperties,
  skippedRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    fontSize: 12.5,
    padding: "3px 0",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  skippedPath: { color: "var(--text-secondary)" } satisfies CSSProperties,
  previewBox: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 16,
    maxHeight: 280,
    overflow: "auto",
  } satisfies CSSProperties,
  warning: {
    display: "flex",
    gap: 10,
    padding: 14,
    borderRadius: 8,
    border: "1px solid color-mix(in srgb, var(--warning) 40%, var(--border))",
    background: "color-mix(in srgb, var(--warning) 10%, transparent)",
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--critical)" } satisfies CSSProperties,
  urlRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  urlInput: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
  } satisfies CSSProperties,
  /** Says WHY Save is disabled — a dead button with no explanation is a bug report. */
  gateHint: {
    marginRight: "auto",
    fontSize: 12.5,
    lineHeight: 1.4,
    color: "var(--critical)",
  } satisfies CSSProperties,
} as const;
