import type { CSSProperties } from "react";

export const s = {
  wrap: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    maxWidth: 900,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  h2: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  filter: { marginLeft: "auto", width: 220 } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  note: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  row: (attached: boolean, attachable: boolean, dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    border: "1px solid " + (attached ? "var(--border-strong)" : "var(--border)"),
    borderRadius: 8,
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
    marginBottom: 6,
    opacity: attachable ? (dragging ? 0.4 : 1) : 0.6,
  }),
  dropTarget: { boxShadow: "inset 0 2px 0 0 var(--accent)" } satisfies CSSProperties,
  handle: (enabled: boolean): CSSProperties => ({
    background: "none",
    border: "none",
    padding: "2px 0",
    lineHeight: 0,
    cursor: enabled ? "grab" : "default",
    color: enabled ? "var(--text-muted)" : "transparent",
    display: "inline-flex",
    flexShrink: 0,
  }),
  checkbox: { width: 15, height: 15, accentColor: "var(--accent)", flexShrink: 0 } satisfies CSSProperties,
  name: {
    fontSize: 13,
    fontWeight: 600,
    flex: 1,
    minWidth: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  dir: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  reason: { fontSize: 12, color: "var(--warn)" } satisfies CSSProperties,
  tokens: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    paddingTop: 4,
    borderTop: "1px solid var(--border)",
    marginTop: 4,
  } satisfies CSSProperties,
  footerTotal: { fontSize: 12, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  footerUntrusted: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  previewPane: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 14,
    fontSize: 13,
    maxHeight: 320,
    overflow: "auto",
  } satisfies CSSProperties,
  previewHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  } satisfies CSSProperties,
  previewName: { fontSize: 12, flex: 1, color: "var(--text-secondary)" } satisfies CSSProperties,
} as const;
