import type { CSSProperties } from "react";

/** Co-located styles for the derived-intent card. */
export const s = {
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "16px 18px",
    borderRadius: 10,
    border: "1px solid var(--border)",
    borderLeft: "3px solid var(--accent)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  head: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  confidence: { marginLeft: "auto", width: 150 } satisfies CSSProperties,
  intent: {
    fontSize: 14.5,
    lineHeight: 1.55,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  scopeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 12,
  } satisfies CSSProperties,
  scopeBox: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  scopeTitle: {
    fontSize: 11,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  list: {
    margin: 0,
    paddingInlineStart: 18,
    fontSize: 13,
    lineHeight: 1.7,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  warnRow: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px solid var(--warn-border, var(--border))",
    background: "var(--warn-bg, var(--bg-surface))",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  meta: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  deferredToggle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: 0,
    border: "none",
    background: "none",
    cursor: "pointer",
    font: "inherit",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  deferredBody: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  deferredItem: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  deferredTitle: { color: "var(--text-primary)" } satisfies CSSProperties,
  skeletons: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
} as const;
