import type { CSSProperties } from "react";

export const s = {
  pageHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    padding: "24px 28px 16px",
  } satisfies CSSProperties,
  pageTitle: { fontSize: 20, fontWeight: 700 } satisfies CSSProperties,
  repoName: { color: "var(--accent-text)" } satisfies CSSProperties,
  pageSubtitle: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginTop: 6,
    maxWidth: 620,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  main: { padding: "0 28px 32px", display: "flex", gap: 20, alignItems: "flex-start" } satisfies CSSProperties,
  listPane: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  loadingStack: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  columns: {
    display: "grid",
    gridTemplateColumns: "1fr 160px 90px 120px",
    gap: 12,
    padding: "0 12px 8px",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  row: (selected: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: "1fr 160px 90px 120px",
    gap: 12,
    alignItems: "center",
    width: "100%",
    textAlign: "left",
    padding: "10px 12px",
    marginBottom: 6,
    borderRadius: 8,
    border: "1px solid " + (selected ? "var(--border-strong)" : "var(--border)"),
    background: selected ? "var(--bg-hover)" : "var(--bg-elevated)",
    cursor: "pointer",
    font: "inherit",
    color: "inherit",
  }),
  name: {
    fontSize: 13,
    fontWeight: 600,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  dir: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  usedBy: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  previewPane: {
    width: 460,
    flexShrink: 0,
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    maxHeight: "calc(100vh - 220px)",
    overflow: "auto",
  } satisfies CSSProperties,
  previewHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderBottom: "1px solid var(--border)",
    position: "sticky",
    top: 0,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  previewName: { fontSize: 12, flex: 1, color: "var(--text-secondary)" } satisfies CSSProperties,
  previewBody: { padding: "14px", fontSize: 13 } satisfies CSSProperties,
} as const;
